/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f4015a41-9139-4728-8c4d-63cdf2bab6e8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vAiTBr57B",
    "aws_user_pools_web_client_id": "6cdaqg1edm3hsf46rd2q68sa63",
    "oauth": {}
};


export default awsmobile;
